name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
            - "Languages/**"
            - "plugins/**"
            - "ext/**"
            - "*.md"
  pull_request:
    branches: [ main ]
    paths-ignore:
            - "Languages/**"
            - "plugins/**"
            - "ext/**"
            - "*.md"

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v3.2.0
      with:
        fetch-depth: 2
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}
    - name: Upload artifacts for x64
      uses: actions/upload-artifact@v3.1.1
      with:
          name: BowPad-x64
          path: bin/Release64/bin/BowPad.exe

